// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using W25Week12CodeFirstApproach;

#nullable disable

namespace W25Week12CodeFirstApproach.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20250331180119_ChangeColumnNameToStudentName")]
    partial class ChangeColumnNameToStudentName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("W25Week12CodeFirstApproach.Standard", b =>
                {
                    b.Property<int>("StandardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StandardId"));

                    b.Property<string>("StandardName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StandardId");

                    b.ToTable("Standards");

                    b.HasData(
                        new
                        {
                            StandardId = 1,
                            StandardName = "Standard 1"
                        },
                        new
                        {
                            StandardId = 2,
                            StandardName = "Standard 2"
                        },
                        new
                        {
                            StandardId = 3,
                            StandardName = "Standard 3"
                        });
                });

            modelBuilder.Entity("W25Week12CodeFirstApproach.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StudentName");

                    b.Property<int?>("StandardId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("StandardId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Name = "John",
                            StandardId = 1
                        },
                        new
                        {
                            StudentId = 2,
                            Name = "Anne",
                            StandardId = 1
                        },
                        new
                        {
                            StudentId = 3,
                            Name = "Mark",
                            StandardId = 2
                        },
                        new
                        {
                            StudentId = 4,
                            Name = "Tina",
                            StandardId = 3
                        });
                });

            modelBuilder.Entity("W25Week12CodeFirstApproach.Student", b =>
                {
                    b.HasOne("W25Week12CodeFirstApproach.Standard", "Standard")
                        .WithMany("Students")
                        .HasForeignKey("StandardId");

                    b.Navigation("Standard");
                });

            modelBuilder.Entity("W25Week12CodeFirstApproach.Standard", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
